### ISSUE TITLE
Cyan vs Blue

### ISSUE THREAD

**Issue by CaptaPraelium** [overdodactyl/ShadowFox#14]
I'm running the latest stable FF57 on Windows.

I notice an inconsistency with the firefox dark theme which seems to be leaking into this project - the battle between highlight colours being either cyan or light blue. As can be seen on the screenshots elsewhere here, the theme uses the light blue colour #0a84ff, specified in the Photon colours as Blue-50, as the highlight for the currently active tab, as well as the progress meter for loading the tab. However, in other places, it is using the Cyan colour that is the default in this project.

Since I am after a consistent browsing experience (and since I find these two tones of 'blue' to clash rather badly and they just look ugly! Every fashionista knows about blue-on-blue...), I have set the highlight colours in this project, to match the blue-50 tone and it's counterpart blue-40:

```
	--primary-accent-color:  #0a84ff; 
	--primary-accent-color-dark: #45a1ff; 
```

This works in some areas, however in others, I am still seeing the cyan colour. It's there in the newly-added AMO theming, it's there on about:* pages, and in some dialogs:

![image](https://user-images.githubusercontent.com/22152831/33766751-05c4517e-dc73-11e7-8942-b151827d74f3.png)

If I can help with this please let me know.

___

Edit: overdodactyl + CaptaPraelium

Running list of color inconsistancies:

- [x] `about:preferences` - majority of highlight colors (colors were inverted here, new code on the way)

- [x]  `about:config` - same as ^^^

**Comment by overdodactyl** [comment]
Hi @CaptaPraelium,

Thanks for bringing up the inconsistency.  We have two things at play here.

(1) For the first day or two of this repository, I wasn't using the variables as they are set now.  When converting, I may have missed some locations (i.e. need to change `darkcyan` to `var(--primary-accent-color)`.

(2) On some `about:` pages, a hacky approach was taken to get the dark appearance - instead of styling all the elements, colors were inverted.  The typical blue inverts to a cyan-like shade, so that's what you are seeing in those cases.  This code is already in the process of being re-written in a better fashion, however.  

It would be really helpful if, on your top comment, you could help maintain a running list of places you run across this issue (I have started the list there).

**Comment by tigerjack** [comment]
@overdodactyl as per my comment to the latest commit, the change broke the dark background color in some pages (like `about:newtab`) but not others (like `about:profiles`).

**Comment by overdodactyl** [comment]
Thanks @tigerjack.  For now I've put those lines back in.  

I need to take a step back and re-work some of my basic file structures/organization.

Sorry for the mishap guys - hope to get everything sorted out ASAP and not scare you all off in the mean time haha.

**Comment by overdodactyl** [comment]
@tigerjack and @CaptaPraelium, if you guy have the chance, would you mind testing the code found in the `code_overhaul` branch?

I think it's a much more simplified version of the current repository (only in terms of userContent.css and associated files) and I think it's a good first step in restructuring the directories.  

I don't want to replace what's currently in the master branch though unless someone else can confirm it's looking alright for them too though haha

**Comment by tigerjack** [comment]
@overdodactyl I don't see the branch. Btw, I've just pulled the updated `master` and I have the same problem, with some pages having a dark background while others having a white one.
Among the pages with a white background I found `about:home newtab plugins privatebrowsing serviceworkers studies` and the `view-source:` pages.

**Comment by overdodactyl** [comment]
@tigerjack, sorry for the confusion.  Someone messaged me on Reddit and told be that branch looked fine, so I guess I too eagerly replaced the master.

The issue you're having is confusing me thought - I'm not sure what could be causing that.  I just tested on a new FF57 and FF59 profile and those all appear to be good.  

At first I was thinking there might be some issues with `@import` statements (@imatimba  just mentioned in another thread some weirdness with the amo styling and `@imports`...but `privatebrowsing` doesn't have it's own .css file...it just relies on the defaults set in userContent.css...

**Comment by overdodactyl** [comment]
@CaptaPraelium,

Colors are no longer being inverted on the `about:preferences` and `about: config` page.  Let me know if that fixed some of the color issues you were seeing on those pages.

**Comment by tigerjack** [comment]
@overdodactyl don't know what to say. I've also restarted firefox with addons disabled (just in case) and I've still the same behavior. I've also tried to run a test, just copy-pasting the content of `color_variable.css` into `userContent.css`; now it works. Can it be a limitation of css submodules? Maybe modules are not imported/processed sequentially and then some color definitions are not found. Just my 2 cents, I'm not a css expert.

**Comment by overdodactyl** [comment]
Thanks for links @tigerjack!

If it's working when copying/pasting, it has to be something weird with `@imports`. I'm guessing it has to do with the order they are imported as you mention.  I restarted my browser ~10 times and noticed once something similar to what you are experiencing.  

Now that userContent.css isn't a ridiculously long file (after segregating out all the pages into their own file), I think it would be appropriate to just remove color_variables.css and place it at the top of userContent.css.

**Comment by overdodactyl** [comment]
@CaptaPraelium, I styled the edit page to match the dark page.

Additionally, I changed the primary accent color to what you have, and the color of the button changed.

Due to some issues with files being imported, the `color_variables.css` file has now just been copy/pasted onto the top of userContent.css

Let me know if these changes have fixed the original issue here

**Comment by overdodactyl** [comment]
Everything here should be fixed -

If not, let me know and I'll reopne

**Comment by CaptaPraelium** [comment]
Almost there!

Sorry for the delay, I was testing this when you made the last update. Lots of positive progress but a small regression.

With the code as it was before you styled the edit page, everything was looking really good. Seeing blue text on all about: pages and also in AMO.

Now the edit page is almost there, but the green text has returned.

 colors file was modified only as such:
	--primary-accent-color: var(--blue-50); 
	--primary-accent-color-dark: var(--blue-60);
This (using the vars rather than copypasting the hex) was working previously.

When I saw your new posts here I updated again, and the cyan is back on AMO and the about pages, and even the edit button, which is strange since you tested that.

The edit page still has a fairly bright background also. Both the green button and that page are in this screenshot. Sorry for the large image, I thought it best to show the full screen this time.

![image](https://user-images.githubusercontent.com/22152831/33800615-91e6e9e4-dd97-11e7-86e8-fe8c82e08651.png)

**Comment by CaptaPraelium** [comment]
Oh I see the problem - I need to modify the user colours in both files since https://github.com/overdodactyl/userContent-tweaks/commit/4e4dde2ff77579ee73729c31b8c38545b5531ca0

Now the only issue remaining is the white background in the edit page

Oh, hey I just noticed you fixed the favicons background, nice!

**Comment by overdodactyl** [comment]
Sorry for the confusion with the colors.  Some users were experiencing issues with the colors being imported from that file...I honestly have no clue why, but everything seems to be good when they are just placed at the top of userContent.css

White background should be a quick fix...but everything else appears to be good in terms of cyan/blue though?

**Comment by CaptaPraelium** [comment]
So, I don't need the color_variables.css? Or I should keep both?

It looks gorgeous! I am not sure if I should be closing this but you are welcome to do so.

**Comment by overdodactyl** [comment]
`color_variables.css` is still utilized right now by `userChrome.css`.  Perhaps I should just copy it to the top of the file there too and deleting `color_variables.css`.

I preferred have only one file with two import statements for simplicity, but I have no clue why that doesn't work for everyone...

**Comment by tigerjack** [comment]
@overdodactyl I'm still experiencing issues, in the sense that both amo ad view-source pages appears with a white backgroun. Just copy-pasting their code in the `userContent.css` file solve the problems.

**Comment by CaptaPraelium** [comment]
It strikes me that this shouldn't really be a performance issue as they are suggesting there. If the browser is attempting to render content which it has not yet fully loaded, then erroneous output should be expected, would that not be a firefox bug? I'm honestly unsure of how it is intended to behave.

Then again, if this is a performance issue, that might explain it because in my case this is a fast modern hexacore pulling the files from an NVMe drive, so I may be less likely to see it.

https://github.com/overdodactyl/userContent-tweaks/issues/9#issuecomment-350531319 Points out that their issues, which reflect yours, are linux-specific. I'm curious as to which OS you are using?

**Comment by tigerjack** [comment]
@CaptaPraelium yep, I'm on Linux. For the moment, I've just solved the problem using a simple bash script to merge all the userContent files into one single file.

**Comment by CaptaPraelium** [comment]
Hmm. It strikes me that this might be a bug in the linux builds of firefox.

I guess this is good news as it allows us to keep the color variables separated as intended and retain the modularity of the code. Well, maybe not so much 'good news', as a 'silver lining'. Of course it means that this can't really work on linux until the bug is fixed, but it sounds like tigerjack has a solid workaround in the meantime. Would you be so kind as to share that script with us tigerjack?

It could probably be argued that a script which concatenates all of this porject's files into one, would be the 'best practice' way to do this anyway, for reasons of performance (see: that stackexchange thread), so maybe this is something which could be used in a future build script.

Regardless, speaking of 'best practice', imports need to work on linux because really the project's modification of any existing user*.css should amount to a single line only, importing the project's css - because while concatenating to a single file is of optimal performance, modularity is most easily maintained.

**Comment by overdodactyl** [comment]
Provided I move webextension-tweaks folder into the userContent-files directory (where it belongs), something like this should work to combine all the userContent files and delete `@import` statements:

```bash
cat ./userContent-files/*/*.css >> userContent.css
grep -v '^@import' userContent.css > stripped.css
mv stripped.css userContent.css
```

Perhaps I could included an `exludes.txt` file where people could list, one entry per line, any files they don't want included in their `userContent.css`.

**Comment by tigerjack** [comment]
My script is similar to the above one. In addition, I've used `yuicompressor` to compress the resulting code.

```
#!/usr/bin/bash

CHROME=userChrome.css
CONTENT=userContent.css
COLOR=color_variables.css
CHROMEDIR=./userChrome-files
CONTENTDIR=./userContent-files
TEMPDIR=./temp

## userchrome
CURRENT=$CHROME
CURRENTDIR=$CHROMEDIR
## clean temp dir
#rm -r "$TEMPDIR/*"
cat "$COLOR" > "$TEMPDIR/$CURRENT"_1
for i in $(find "$CURRENTDIR/" -type f -name "*.css"); do cat $i >> "$TEMPDIR/$CURRENT"_1; done
grep -v '^\@import' "$TEMPDIR/$CURRENT"_1 > "$TEMPDIR/$CURRENT"_2
java -jar yuicompressor-2.4.8.jar --type css "$TEMPDIR/$CURRENT"_2 -o $CURRENT

## usercontent
CURRENT=$CONTENT
CURRENTDIR=$CONTENTDIR
cat "$COLOR" > "$TEMPDIR/$CURRENT"_1
for i in $(find "$CURRENTDIR/" -type f -name "*.css"); do cat $i >> "$TEMPDIR/$CURRENT"_1; done
grep -v '^\@import' "$TEMPDIR/$CURRENT"_1 > "$TEMPDIR/$CURRENT"_2
java -jar yuicompressor-2.4.8.jar --type css "$TEMPDIR/$CURRENT"_2 -o $CURRENT

## clean temp dir
#rm -r "$TEMPDIR/*"
```
I've not done much to optimize the script, so feel free to blame me.

**Comment by CaptaPraelium** [comment]
I wonder if it's related here... as mentioned I'm not on Linux and this "imports not working" thing does seem to be specific to firefox on linux... But I've noticed the 'reduce white flashes' script and by reading it, I expect that my background should be dark grey before the page loads... but I still see a lot of white flashes here and there when I load/reload pages.

Thought I should mention it...

**Comment by tigerjack** [comment]
@CaptaPraelium I used to have the same problem, but now with a unique large `userContent.css` I don't see any white flash anymore.

**Comment by CaptaPraelium** [comment]
Oh well, even if that code is the only thing in my userchrome it is not working, so I guess that's a separate issue.

**Comment by overdodactyl** [comment]
Thanks for sharing that script @tigerjack! I actually haven't come across `yuicompressor` before - I'll have to check it out :)  If you're ok with it, I might end up adding something like that to the repo (with credit to you, of course).  

@CaptaPraelium, in reference to the white flash, where/when are you seeing it?  I have the necessary fixes for it in both the userContent and userChrome files.  

Unfortunately, you will still get with flashes on some websites that have it built into their own code.  For me, Reddit is one example of a site like this.  You can create individual fixes (fairly easily in the cases I've run across), but there's no "catch all" solution for this scenario.  For Reddit, all that's needed was 

```css
html {
    background-color: #292929 !important;
}
```

**Comment by elerch** [comment]
@overdodactyl - I can confirm what @tigerjack is seeing regarding view source. I have FF with this repo checked out in my profile's chrome directory on both Mac and Linux. On Mac, view source is styled with the changes here. On Linux, view source has the default styling. Pasting the userContent-files/webpages/view_source.css content directly into userContent.css file addresses the issue I see on Linux.

I went searching for a bug on bugzilla, and it looks like someone else has noticed the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1416184

**Comment by elerch** [comment]
I should also mention that the scripts above are a bit simplistic (and didn't work for me for about:newtab, not sure if that's related). As css is order-dependent the contents of the files should maintain positional order with the import statements in the base. So the base css should be parsed and the contents of the import added at that spot.

I believe [clean-css](https://github.com/jakubpawlowicz/clean-css) handles import statements, so that could be used directly rather than concatenation+yuicompressor technique @tigerjack is using.

**Comment by overdodactyl** [comment]
Thanks @elerch for letting me know!

I appreciate the bugzilla link as well..it's good to see this has been acknowledged by Firefox! Unfortunately with a P3 priority and no apparent work being done in the past month, I'm not too hopeful of this being resolved in the near future.   

Obviously my hope would be to make this work across all platforms without any issues...so something needs to be done here on my end...  but I'm struggling to decide what the "best" approach would be.   Maybe you (and @tigerjack and @CaptaPraelium ) have some ideas/opinions?

Hoping someone has a better idea than me, but if not, it seems like the available options would be:

(1) Put everything in userContent.css

Advantages:

- Easy fix, easy to maintain

Disadvantages:

- Makes it difficult for each user to pick and choose what tweaks they want.  

(2)  Upload a script similar to what was discussed above to the repo

Advantages:

- User could pick what changes they want with more ease

Disadvantages:

- In addition to keeping up-to-date with the repo, a user would have to continually run this script with each update

- Not all users are familiar with how to run a script

and, last but not least, perhaps the best option:

(3) Create multiple versions of userContent.css.  For example,

`userContent_1.css`

`userContent_2.css`

....

where `userContent_1.css` may contain everything, `userContent_2.css` may contain just changes to just the `about` pages, `userContent_3.css` about pages + amo store etc.

Advantages:

- More "easy" options for users

Disadvantages:

- Hard to create a userContent.css file for *every* combination of options (I guess I could create a script to create a file for every possible combination of concatenations...but that might just cause there to be way too many options)

- More maintenance work.  Would this be worth the effort? I'm not sure how users are going to be using this repo.  For example, is anyone going to want changes to the about pages, but not the addon store?  Are there users who would want the preferences page dark, but not their home page?

**Comment by overdodactyl** [comment]
clean-css looks pretty interesting/promising!

Admittedly, based on a very quick look, it might take me a while to dive into that/learn how it all works though haha

**Comment by elerch** [comment]
IMHO I think having things broken out the way you do works well. You can mitigate the disadvantages in #2 by performing an automated "build" that deploys downloadable combined userContent/userChrome files for users to download. [Travis](https://travis-ci.org/) has good integration with Github and could probably play a role there.

**Comment by overdodactyl** [comment]
I've heard of Travis, but haven't ever looked into it/utilized it.  Looks like a pretty promising option if I can get it working haha

**Comment by overdodactyl** [comment]
Gulp seems like a good approach to combining css file as well:

https://travishorn.com/integrating-multiple-stylesheets-in-a-single-site-e720256edcee?gi=f792697a6aa

**Comment by tigerjack** [comment]
Yep actually the script is, as I admitted before, very minimalistic. I've just coded it as a quick workaround hoping for better options in the future. Also, @elerch , maybe your problem is that the `userContent.css` file, apart from the @import statements, contained also a general section, the one below the comment `/* Basic changes fundamental to all pages *`. I should have mentioned that I put a simple `global.css` file in the `userContent-files` directory that contains only those few lines.

As for the available options, I think you can continue to use your approach with import and everything to simplify the development, while at the same time creating a way for the user to combine the different css files into a single output file (actually two, `userContent.css` and `userChrome.css`). I mean, it's not so hard for the average github user to run a simple script; most of us are used to `Makefile`s and other kind of build options.

**Comment by overdodactyl** [comment]
I think I've found a fairly good solution via [gulp](https://github.com/mariocasciaro/gulp-concat-css) - which helps merge various `.css` files into one. This would allow me to keep the project separated into multiple directories, while having an easy way for users/myself to merge them (granted, users would have to install `gulp`, but I don't think that's a big deal).  The main directory would contain  a new `gulpfile.js` file in the root folder, and inside it would contain commands for various combinations.  For example,

```js
'use strict';

var gulp = require('gulp');
var concatCss = require('gulp-concat-css');

/* Add everything to userContent */
gulp.task('userContent_all', function() {
  return gulp.src(['color_variables.css', 'userContent-files/all_pages.css', 'userContent-files/*/*.css'])
    .pipe(concatCss('userContent.css'))
    .pipe(gulp.dest('.'));
});

/* Only make changes to addons.mozilla.org */
gulp.task('userContent_amo', function() {
  return gulp.src(['color_variables.css', 'userContent-files/all_pages.css', 'userContent-files/webpages/amo_store.css'])
    .pipe(concatCss('userContent.css'))
    .pipe(gulp.dest('.'));
});
```
Running `gulp userContent_all` would create `userContent.css` with all changes in this repo.  Likewise, `gulp userContent_amo` would only include the changes to addons.mozilla.org.  By default, the repo would always contain the product of `gulp userContent_all`.  For users that want something unique, the could use a predefined function I've added to `gulpfile.js`, or they could create their own (and hopefully submit a pull request with it so everyone can benefit :) ).  

Then, to update the repo, a user would either need just `git pull` or something like `git pull && gulp userContent_amo`.  

Anyone have any thoughts on that?

**Comment by overdodactyl** [comment]
As for creating official builds/releases @elerch, I like the idea, but being able to do so would depend on how frequently changes need to be made to keep up with FF changes (how often that will be has yet to be seen).  It would be nice to have a release product, but if I'm making changes daily, I'm not certain that would be as practical of an approach

**Comment by elerch** [comment]
The gulp solution I think works fine. IIRC clean-css uses node anyway, so both options require node be installed, and node is available on all targeted platforms. Ultimately what I would personally do is have a script that does the pull+concat process to stay up to date, but I think it's easy enough to document the manual steps in a README as well.

**Comment by overdodactyl** [comment]
That's a good idea to include a basic script to do both commands.

I'll look into how to make releases for a GitHub project as well (never have done that).  If I don't have to continually make changes to the repo, I think that would be a good approach for people who don't want to make any modifications to this repo.  All it would need to include is  the combined `userContent.css` and `userChrome.css` files.

**Comment by overdodactyl** [comment]
I've given this approach a try (see the modified repo and the corresponding [wiki entry](https://github.com/overdodactyl/ShadowFox/wiki/Customizing-what-tweaks-are-included-in-your-userChrome-Content-files)).

Figured this approach was worth a try, but let me know if anyone has and issues or concerns with it, I'm open to changes.  

For those of you on Linux, can you use a single `@import` statement, or was the issue with nested ones?

i.e. in your normal `chrome` directory, could you add `@import "ShadowFox/userContent.css";` and have everything work? Or do you need to add all these changes to any previous userContent.css file?

**Comment by CaptaPraelium** [comment]
It looks like I'm late to the party here.... Hopefully no toooo late :)

The new process, when compared to 'download the zip and extract it here", is incredibly complex and time consuming, this seems like nothing to devs like us but is very prohibitive to an end-user. 

I don't mind doing this sort of thing for work, but I wouldn't bother with it here at home (where the point of this project is to keep my screen dark on my gaming PC at night), and I'm sure that people who don't do this for work will start to look at the instructions and just walk away... Honestly it's already reached that point for me. I looked at it and thought, I don't really want git on this PC, I don't want node.js certainly, I don't even know what NPM is (sorry I might be a dev but it's not in my usual toolchain) and I'm not sure if it's included in one of the other packages or I need to install it, the webpages for those projects don't really make it clear ... Yeh you see where I'm going with this.

I spent some time considering, when reading @overdodactyl response to my installer issue, what would determine the best approach, and realised that it is really about determining who the target audience is for this project - and I think the same applies here. If the target audience is professional web devs, I think you're on the right track... But if your audience is anything beyond that, they will read things like this:

"As an asynchronous event driven JavaScript runtime, Node is designed to build scalable network applications. In the following "hello world" example, many connections can be handled concurrently. Upon each connection the callback is fired, but if there is no work to be done, Node will sleep."

...And just nope.avi right out of here. I think it would be a shame to limit the scope of the project so heavily.

**Comment by overdodactyl** [comment]
HI @CaptaPraelium,

You bring up excellent points...it is a little more convoluted than one would hope for the average user.  

It is worth pointing out, however, that the all stuff with git, node.js, and gulp are currently only necessary if you want a way to pick which files are included.  The main repo still contains a fully functional, all inclusive userChrome.css and userContent.css that will work across all platforms.

Unfortunately, I'm somewhat at a loss for what the best approach to take is. 

`@imports` seemed like the most straightforward, easy approach.  Unfortunately, this isn't working for Linux users (which are by no means a tiny fraction of people).   Not everyone is going to be like @imatimba, @tigerjack, and @elerch who have both the ability and patience to see it wasn't working, open up an issue, test on various platforms etc.  They're going to see it doesn't work and simply not use the repo...end of story. 

So...the question once again becomes, what to do? To me, the problem is we have various goals, and not all of them seem to be compatible with each other.  Ideally, this project would

- Work seamlessly across all platforms

- Have a simple way to download/setup

- Be easy to update

- Easy customization

What approach were you thinking be best?

I guess I could also keep the userChrome/Content.css files on GitHub for non-Linux users as well.

**Comment by overdodactyl** [comment]
Could anyone on Linux be so kind as to try using and `@import` statement for a file that was working using the following format?

`@import url(./css/buttons/buttons_on_navbar_classic_appearance.css);`

This is how all the imports are written by Aris-t2 (Classic Theme Restorer author) on his repo:
https://github.com/Aris-t2/CustomCSSforFx

Maybe I just need to use the `url` approach?

**Comment by tigerjack** [comment]
What the... It seems to work now.

**Comment by overdodactyl** [comment]
@tigerjack...you mean the `@import` works using `url`?? (If so, hooorahh!)

**Comment by tigerjack** [comment]
@overdodactyl well, at the moment I'm not seeing any issue at all. Let's hope.
Just a curiosity: the structure of the url is equal also on windows (i.e. you don't have to convert backslash to forward slash or something)?

**Comment by overdodactyl** [comment]
@tigerjack, I _think_ it's the same on WIndows in this case (hopefully?)

And just to make sure, you tried that import statement on the old version where it wasn't working, not the current userContent.css file that has everything mushed into one file?

If so, I guess I can go back to the old userContent.css version, and avoid all this mess with `node.js`, `gulp` and so forth..

**Comment by tigerjack** [comment]
@overdodactyl yep, the master branch of my offline repository was at https://github.com/overdodactyl/ShadowFox/commit/cf3032b561ada681463df7df64bcf9700b80273f ; all my changes were on different branches. Before you proceed, just make sure that others won't have problems.

**Comment by imatimba** [comment]
@overdodactyl using:  
```
@import url(./userContent-files/webpages/view_source.css);
@import url(./userContent-files/webpages/amo_store.css);
```
in the latest commit before the gulp restructure and amo/view-source are default white.  
On the other hand the latest commit works without issues.

**Comment by overdodactyl** [comment]
Thanks for testing that @imatimba! Did you try that on your Linux distros or on Windows 10?

@tigerjack, that was Linux you had success using those lines, correct?

**Comment by imatimba** [comment]
Linux, Windows works fine with the normal import, didn't test the url import but I suppose it works too.

**Comment by CaptaPraelium** [comment]
Just real quick because I can see everyone is active here right now, I think that it is fine to have a more complex method only if customisation is required. Sorry, I didn't realise the full project is in those two files as it is, and I think that for the end-user, that's fine.

I'll test with the @import url(.....) on Win10 right now.

**Comment by overdodactyl** [comment]
I'm seeing some references online that also say to use quotes.... i.e something like

`@import url('/css/layout.css');`

could you try that @imatimba?

@CaptaPraelium, I would agree...but hopefully we can get this `@import` thing working and wouldn't hae to worry about it anyway :) I think that would be easier for everyone (me included)

**Comment by CaptaPraelium** [comment]
Both `@import url('file')` and `@import url(file)` are working here on windows.

**Comment by overdodactyl** [comment]
Thanks @CaptaPraelium,

So for mac and windows, we seem to have at least three choices:

- `@import url('file')`
- `@import url(file)`
- `@import 'file'`

Mozilla's site seems to suggest these should work and give these as examples:
```
@import 'custom.css';
@import url("chrome://communicator/skin/");
```

They do have this specification: **"These rules must precede all other types of rules, except @charset rules"**

@imatimba and @tigerjack in the cases these weren't working for you, were all the imports at the very top of you files?

**Comment by elerch** [comment]
I concur with @imatimba. I changed the view_source line to:

@import url('./userContent-files/webpages/view_source.css');

moved it to the top line of the file and restarted FF to be sure the changes were picked up. View source remained default white. I tried with and without quotes on linux.

This was all using commit d9912a9 as the base for the changes.

**Comment by overdodactyl** [comment]
Thanks @elerch,

As one last hope, can you add

```css
@import url('./color_variables.css');
```
above that `import` statement you wrote and try that?

**Comment by elerch** [comment]
Sorry - no change when doing that.

**Comment by overdodactyl** [comment]
Thanks for checking @elerch.

Whelp, given Mozilla has that syntax on their website, I think I might chalk this up as a Firefox bug (probably the one you provided the link to).

In an attempt to help everyone find something that works for them, perhaps I will keep everything in the repo now, add the old userContent/Chrome files with all the `@import` statements, and look into creating "releases" containing the two complete files.  

Then users have the choice of (1) using the repo as is with just the two files (2) using import statements if their OS accepts them or (3) can use `gulp` to create a custom combination of snippets (I'll add some more default options to `gulpfile.js`).  

For now, at least, that's the best solution I can think of :(

**Comment by CaptaPraelium** [comment]
I think that a github 'release' that just contains the two files would be excellent. Not only does it make installation simple, it makes the whole project less daunting for new guys, and also makes updating simple when something gets updated in FF and breaks it...

For those who need to customise, I can't help but think that it would be easier to just edit those files directly, than to setup a toolchain. 

That being said, there is the new 'linux subsystem for windows' which allows Windows users to run Ubuntu (among other distros) shells and commands, so this could provide a solution which would be easier for you to maintain as your linux process will work exactly the same way on windows once that subsystem is enabled (a tickbox) and Ubuntu installed (a button press).

I can't help but wonder, what it is that gulp is doing, which couldn't be performed by simple file concatenation performed by a shell script?

**Comment by overdodactyl** [comment]
Sounds good - I have to imagine you can create releases with just the two files, I'm not seeing an easy way to do so right of the bat though. 

As for gulp, I think it's biggest advantage is that it "concatenates css files, bubbling up @import statements (as per the standard), and optionally rebasing urls and inlining local @import statements."  In other words, it helps makes sure everything is concatenated in a proper order, all imports are placed at the top of the file, etc.  For this project, perhaps it's not necessary.  

It does provide a nice easy way to create various options/combinations for a user to put together, however.  Another perk is simply less upkeep and worrying about cross compatibility for me.

**Comment by overdodactyl** [comment]
I'll get out an official "release" today.

If anyone has any additional comments/concerns/better ideas for how this all should be approached, I think it would be best to open up a new issue on the subject :)
